#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
# TaskDefinition: "{{AWS_TASK_DEFINITION_ARN}}"
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-northeast-1:187091248012:task-definition/fcjresbar-task-be:76
        LoadBalancerInfo: 
          ContainerName: "backend"
          ContainerPort: 5000
